### ISSUE TITLE
Using the underscore as it is being used as a standard already 

### ISSUE THREAD

**Issue by yanickrochon** [tc39/proposal-private-fields#15]
The underscore character `_` has been used forever by JavaScript programmers to denote a field which should not be accessed directly. Why not just make this official?

```
class Foo {
  _a;
  _b;

  suffix;

  constructor(a, b) {
    this._a = a;
    this._b = b;
  }

  get value() { return this._a + this._b + (this.suffix || ''); }
}

var foo = new Foo(2, 3);

foo.value;   // -> 5
foo.suffix = '!';
foo.value;   // -> 5!
foo._a;      // TypeError: cannot access private property _a
foo.a;       // -> undefined
```
### `__proto__`, etc.

Since idenfifiers such as `foo.__proto__` should be accessible, only identifiers starting with an underscore (i.e. `/^_.*?[^_]$/`) within a class context should be marked as private.

**Comment by zenparsing** [comment]
Unfortunately, we don't want to do that because it would require changing the behavior of normal property lookup.  Also, I think that underscore-prefixed names will still have a place in a world with private fields.  In my opinion (which not everyone agrees with), underscore-prefixed names can be used to indicate properties and methods which are intended for usage by subclasses but not by clients.  

Essentially, I don't think we need "protected" fields:  underscore prefixes fill that gap quite nicely already.

**Comment by yanickrochon** [comment]
I don't understand the second part of your argument; you are discussing having private fields in JavaScript, but ignore a standard used across most JavaScript programmers to do just that in the grounds of "underscore-prefixed names will still have a place in a world with private fields" ?

My point is to actually make this norm a standard, whereas all I see here is a proposal to yet add more complexities to JavaScript. Besides, don't you want more input before closing an issue? Instead of discarding it. (Need I remind that closed issues ore not shown by default when listing issues on Github?) Otherwise this whole discussion doesn't seem objective to me.

**Comment by zenparsing** [comment]
Apologies @yanickrochon for closing so quickly.  Your proposal is actually a non-starter since it would change the meaning of the existing property lookup syntax.  That we cannot do.
