### ISSUE TITLE
On private slot redefinition, throw or reset to undefined?

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-private-fields#22]
In https://zenparsing.github.io/es-private-fields/#sec-addinternalslots , if an internal slot is defined twice (which can happen by having the super constructor return an existing instance), the field is re-set to undefined. Another possible semantic is to throw, or even leave the old value in. What are the advantages and disadvantages of these three approaches? I don't see any implementation concerns pointing towards any one of the three options, but it seems to me like it'd be a programming error that would be useful to report. What do you think? @rossberg-chromium

**Comment by zenparsing** [comment]
For now at least, I've changed it to throw.

**Comment by erights** [comment]
> For now at least, I've changed it to throw.

I prefer throw. 

First, I no longer think there are any hard integrity issues at stake here:
It is hard to see how a malicious client could foist the re-initialization situation on a properly written defensive class, or how a malicious subclass could foist this situation on a properly written defensive superclass. Although a maliciously superclass clearly could foist this situation on an innocent subclass, it is unreasonable to expect subclasses to defend against their superclasses. If A is a superclass of B, then A will generally be in B's reliance set -- the correctness of B's behavior is allowed to rest on the assumption of A's correct behavior. Without very explicit arrangement to the contrary, a normal defensive class would not engage in super-override or allow its inheritance chain to be manipulated. A normal defensive derived class would permanently inherit only from a proper defensive superclass. Thus, in the absence of an explicit arrangement to the contrary, normal defensive code would not encounter the re-initialization issue.

The attack by feeding in a bizarre [[newTarget]] does need to be considered. It does create hazards, but, AFAICT, not re-initialization hazards.

Although there are plausibly no hard integrity issues at stake on re-initialization, nevertheless, much defensive code will be flawed. If such a situation does happen, it is highly unlikely to be useful and more likely to be an integrity threat caused by an overlooked vulnerability. Better to fail fast and before doing any more damage.

**Comment by zenparsing** [comment]
I agree, and thanks for the exploration here.
