### ISSUE TITLE
Property accessor shorthands

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-private-fields#5]
There should be a convenient way to write a simple struct-like class with simple getters and setters for the instance variables.  This is too cumbersome:

``` js
class Simple {
    @a;
    @b;
    @c;
    get a() { return @a }
    set a(v) { @a = v }
    get b() { return @b }
    set b(v) { @b = v }
    get c() { return @c }
    set c(v) { @c = v }
}
```

There should also be a convenient way to implement immutable classes, with a shorthand for something like:

``` js
class Imm {
    @a;
    @b;
    @c;
    get a() { return @a }
    get b() { return @b }
    get c() { return @c }
}
```

**Comment by zenparsing** [comment]
A strawman syntax:

``` js
class PatternTreeNode {

    public @name;
    public @initializer;
    public @children = [];
    public @target = "";
    public @skip = 0;
    public @array = false;
    public @rest = false;

    constructor(name, init, skip) {

        @name = name;
        @initializer = init;
        @skip = skip | 0;
    }
}

class Immutable {

    get @name:String = "skdjf";
    get @age:Number = 123;

    constructor(name:String, age:Number) {

        @name = name;
        @age = age;
    }
}
```

**Comment by zenparsing** [comment]
An opinion piece (for Java) which discusses why "default" getters and or setters are a bad idea anyway:

http://www.javaworld.com/article/2073723/core-java/why-getter-and-setter-methods-are-evil.html

**Comment by domenic** [comment]
This is a one-hour-after-waking-up thought, so take it with a grain of salt, but in my C# experience I found that auto-getters are very valuable while auto-setters are not. (They were only used, really, to work around a design flaw in some C# UI frameworks, which could only bind to get/set accessors instead of to public fields directly.)

I can't really think of a use case where I'd want your `class Simple`, whereas your `class Imm` I would use all the time.

I also vaguely remember reading some C# blog pieces about this type of thing but can't remember any good keywords. I might try pinging C# people on Twitter later today.

**Comment by zenparsing** [comment]
I think if you want "public" fields, then you probably just want to use object literals or simple classes with no private state.
